### ISSUE TITLE
Time Shortcode: Allow to pass an attribute to parse the date string relative to current time

### ISSUE THREAD

**Issue by ocean90** [Automattic/o2#113]
Times are currently [relative to the post/comment time](https://github.com/Automattic/o2/blob/bff0d49ebc0f76aa9ec56eea916d9492418ec5a8/modules/time-shortcode/load.php#L17-L26). On w.org we have more or less the same shortcode but it supports an additional attribute to make dates relative to current time. This is useful for recurring meetings as you can see on https://make.wordpress.org/core/ (sidebar).

Source of the w.org plugin: [time-shortcode.php.txt](https://github.com/Automattic/o2/files/531114/time-shortcode.php.txt)

**Comment by claudiulodro** [comment]
I've got an open pull request for a refactor and bug fix of o2's time shortcode ( https://github.com/Automattic/o2/pull/83 ). I'll work this into that.

**Comment by claudiulodro** [comment]
These changes are ready and should make their way into master when that pull request gets merged in. Once that happens, you may also want to use the latest version of the shortcode on .org since this new version is heavily unit tested and maintained. The working version is at https://github.com/claudiulodro/o2/tree/time-shortcode/modules/time-shortcode right now.

**Comment by pento** [comment]
Fixed in #83.
