### ISSUE TITLE
JavaScript error while posting

### ISSUE THREAD

**Issue by swissspidy** [Automattic/o2#5]
`Uncaught TypeError: Cannot read property 'top' of undefined` on line 126 of `new-post.js`.

The line in question: `scrollTop: $( '#post-new' ).offset().top - 50`. There's no `#post-new` element on the page.

**Comment by georgestephanis** [comment]
Are you getting this while using the p2-breathe theme?

**Comment by georgestephanis** [comment]
I wonder if something else may be causing an onSaveError call which removes it before the 200ms later callback triggers?

https://github.com/Automattic/o2/blob/3b79904a626e6e63551a40eb3330305d664be4c8/js/views/new-post.js#L148

**Comment by swissspidy** [comment]
Yes, I'm using p2-breathe.

First I thought there was en error because of #4, but `onSaveError` is never called, only `onSaveSuccess`.

**Comment by aymanalzarrad** [comment]
Hello :) I have also noticed that `onSaveError` is never called. However, I think the 200ms is actually the cause of the error as that is resulting in the callback being called when the post had already changed id to `post-{ID}` which is too late as the '#post-new' target is basically gone.
Couple of thoughts:
- Make the `post-new` a class or even a data attr instead of an id?
or
- Delay the id switch from `post-new` to `post-{ID}` ? ( I couldn't really locate where the switch is happening )
or
- Eliminate the timeout on the scroll?
