### ISSUE TITLE
Readme plugin should like to wp.org/plugins/

### ISSUE THREAD

**Issue by Ramoonus** [Automattic/o2#6]

**Comment by beaulebens** [comment]
This plugin is intentionally not being released to the wp.org repo, because it's not in a great state for end users to just install and use. We are making the code available here more as a curiosity for developers, and do not recommend that it is used in production.

If that changes, then we will put it in the .org repo and update things accordingly.

**Comment by Ramoonus** [comment]
i made a typo
like should be link

and I will provide a pull reuqest myself

PS; i thought you were a book character
